{"uuid":"0e99b504-63eb-48a0-b671-948e3c6e1164","historyId":"73de0c240da6344d377a77747aa939aa","fullName":"com.automationframework.tests.ProfileTest.updateProfileScenarios","labels":[{"name":"package","value":"com.automationframework.tests.ProfileTest"},{"name":"testClass","value":"com.automationframework.tests.ProfileTest"},{"name":"testMethod","value":"updateProfileScenarios"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ecommerce-automation"},{"name":"subSuite","value":"com.automationframework.tests.ProfileTest"},{"name":"host","value":"Agilas-MacBook-Pro.local"},{"name":"thread","value":"42270@Agilas-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"updateProfileScenarios","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.RuntimeException: Row not found: 3","trace":"java.lang.RuntimeException: java.lang.RuntimeException: Row not found: 3\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:812)\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:737)\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:915)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\n\tat org.testng.TestRunner.run(TestRunner.java:619)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\n\tat org.testng.TestNG.run(TestNG.java:1101)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: java.lang.RuntimeException: Row not found: 3\n\tat com.automationframework.util.ExcelUtil.getCellData(ExcelUtil.java:29)\n\tat com.automationframework.util.TestDataProviders.getProfileData(TestDataProviders.java:78)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)\n\t... 24 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1757124139371,"stop":1757124139374}